# Generated by Django 2.2 on 2019-04-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_allow_null_in_projects_groups_and_layers_file'),
        ('estimators', '0002_estimator_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimator',
            name='image_files',
            field=models.ManyToManyField(related_name='files', to='projects.File'),
        ),
    ]
