# Generated by Django 2.2 on 2019-04-23 15:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimators', '0004_imagetile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segments', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='segments')),
                ('estimator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimators.Estimator', verbose_name='estimator')),
                ('image_tile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estimators.ImageTile', verbose_name='image tile')),
            ],
        ),
    ]
