# Generated by Django 2.2 on 2019-04-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimators', '0007_imagetile_tile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimator',
            name='image_files',
            field=models.ManyToManyField(blank=True, related_name='files', to='projects.File'),
        ),
    ]
