# Generated by Django 2.2.2 on 2019-08-09 18:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_set_in_beta_default_true'),
        ('estimators', '0011_fix_unique_on_annotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictingJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('estimator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimators.Estimator', verbose_name='estimator')),
                ('image_files', models.ManyToManyField(blank=True, to='projects.File')),
            ],
        ),
    ]
