# Generated by Django 3.0.5 on 2020-05-21 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimators', '0015_estimator_configuration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimator',
            old_name='image_files',
            new_name='_image_files',
        ),
    ]
