# Generated by Django 3.0.5 on 2020-05-21 20:34

import os

from django.db import migrations


def migrate_image_files(apps, schema_editor):
    Estimator = apps.get_model('estimators', 'Estimator')
    for estimator in Estimator.objects.all():
        estimator.image_files = [
            os.path.join(f.path, f.name) for f in estimator._image_files.all()
        ]
        estimator.save()


class Migration(migrations.Migration):
    dependencies = [
        ('estimators', '0017_estimator_image_files'),
    ]

    operations = [
        migrations.RunPython(migrate_image_files, migrations.RunPython.noop),
    ]
