# Generated by Django 3.0.5 on 2020-05-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimators', '0018_migrate_estimator_image_files'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='imagetile',
            name='estimators__file_id_24b8e8_idx',
        ),
        migrations.AddField(
            model_name='imagetile',
            name='source_image_file',
            field=models.CharField(max_length=255, null=True, verbose_name='source image path'),
        ),
        migrations.AlterUniqueTogether(
            name='imagetile',
            unique_together={('source_image_file', 'col_off', 'row_off', 'width', 'height')},
        ),
        migrations.AddIndex(
            model_name='imagetile',
            index=models.Index(fields=['source_image_file', 'index'], name='estimators__source__23e32a_idx'),
        ),
    ]
