# Generated by Django 3.0.5 on 2020-05-21 20:59

import os

from django.db import migrations


def migrate_file(apps, schema_editor):
    ImageTile = apps.get_model('estimators', 'ImageTile')
    for image_tile in ImageTile.objects.all():
        f = image_tile.file
        image_tile.source_image_file = os.path.join(f.path, f.name)
        image_tile.save()


class Migration(migrations.Migration):
    dependencies = [
        ('estimators',
         '0019_add_image_tile_source_image_file_and_fix_indexes_constraints'),
    ]

    operations = [
        migrations.RunPython(migrate_file, migrations.RunPython.noop),
    ]
