# Generated by Django 3.0.5 on 2020-06-02 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_remove_layer_file'),
        ('estimators', '0021_make_image_tile_source_image_file_non_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetile',
            name='file',
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='projects.File',
                verbose_name='file'),
        ),
    ]
