# Generated by Django 3.0.5 on 2020-06-02 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_remove_layer_file'),
        ('estimators', '0023_auto_20200602_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetile',
            name='project',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tiles',
                to='projects.Project',
                verbose_name='project'),
        ),
    ]
