# Generated by Django 3.0.5 on 2020-06-12 17:26

from django.db import migrations, models
import estimators.models


class Migration(migrations.Migration):

    dependencies = [
        ('estimators', '0025_auto_20200612_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetile',
            name='tile_file',
            field=models.FileField(
                upload_to=estimators.models.tile_images_storage_path,
                verbose_name='image'),
        ),
    ]
