# Generated by Django 2.1.7 on 2019-02-21 13:45

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('layer_type', models.CharField(choices=[('R', 'Raster'), ('V', 'Vector')], default='R', max_length=1)),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='layerimage',
            name='layer',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='project',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='slug',
        ),
        migrations.AddField(
            model_name='layer',
            name='area_geom',
            field=django.contrib.gis.db.models.fields.PolygonField(default=None, srid=4326),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer',
            name='extra_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='LayerImage',
        ),
        migrations.AddField(
            model_name='layer',
            name='layer_collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.LayerCollection'),
        ),
    ]
