# Generated by Django 2.1.7 on 2019-02-22 01:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190222_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layercollection',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='layercollection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='layercollection',
            name='layer_type',
        ),
        migrations.RemoveField(
            model_name='layercollection',
            name='name',
        ),
        migrations.RemoveField(
            model_name='layercollection',
            name='project',
        ),
        migrations.RemoveField(
            model_name='layercollection',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='layercollection',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='layer',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.LayerCollection'),
        ),
        migrations.AddField(
            model_name='layer',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='layer_type',
            field=models.CharField(choices=[('R', 'Raster'), ('V', 'Vector')], default='R', max_length=1),
        ),
        migrations.AddField(
            model_name='layer',
            name='name',
            field=models.CharField(default='---', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='layer',
            name='slug',
            field=models.SlugField(default='---'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.RemoveField(
            model_name='layer',
            name='layer_collection',
        ),
        migrations.AlterUniqueTogether(
            name='layer',
            unique_together={('project', 'slug')},
        ),
    ]
