# Generated by Django 2.1.7 on 2019-02-24 05:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20190222_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='map',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.RemoveField(
            model_name='map',
            name='is_private',
        ),
        migrations.AlterUniqueTogether(
            name='map',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='maplayer',
            unique_together={('map', 'layer'), ('map', 'order')},
        ),
    ]
