# Generated by Django 2.1.7 on 2019-02-24 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20190224_0502'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='layer',
            unique_together={('project', 'date')},
        ),
    ]
