# Generated by Django 2.1.7 on 2019-02-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20190224_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='layer',
            unique_together={('project', 'name', 'date')},
        ),
    ]
