# Generated by Django 2.1.7 on 2019-02-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20190224_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='center',
        ),
        migrations.RemoveField(
            model_name='map',
            name='zoom',
        ),
    ]
