# Generated by Django 2.2.1 on 2019-05-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_allow_null_in_projects_groups_and_layers_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='in_beta',
            field=models.BooleanField(default=False, verbose_name='In Beta'),
        ),
    ]
