# Generated by Django 2.1.7 on 2019-03-09 16:27

from django.db import migrations
from django.conf import settings


def create_default_user_profiles(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    UserProfile = apps.get_model('projects', 'userprofile')

    users_without_profile = User.objects.filter(userprofile__isnull=True)
    for user in users_without_profile:
        UserProfile.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_userprofile_in_beta'),
    ]

    operations = [
        migrations.RunPython(create_default_user_profiles),
    ]
