# Generated by Django 2.2.1 on 2019-06-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_create_default_user_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='in_beta',
            field=models.BooleanField(default=True, verbose_name='In Beta'),
        ),
    ]
