# Generated by Django 2.2.6 on 2020-01-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_auto_20200122_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='free',
            field=models.BooleanField(default=True, verbose_name='Free'),
        ),
    ]
