# Generated by Django 2.2.7 on 2020-03-30 18:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_delete_api_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapikey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userapikey',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='userapikey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
