# Generated by Django 3.0.5 on 2020-06-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_remove_layer_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='migrated',
            field=models.BooleanField(default=False),
        ),
    ]
