image: python:3.6

test:
  variables:
    LC_ALL=C.UTF-8
    LANG=C.UTF-8
  script:
    - apt-get update -qy
    - apt-get install -y python3-dev python3-pip
    - pip install pipenv
    - pipenv install
    - python manage.py test
