fail_fast: true
repos:
  - repo: local
    hooks:
      - id: autoflake
        files: terra/
        name: Remove unused variables and imports
        entry: bash -c ' autoflake "$@"; git add -u' --
        language: python
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variables",
            "--expand-star-imports",
            "--ignore-init-module-imports",
          ]
        files: \.py$
      - id: isort
        files: terra/
        name: Sorting import statements
        entry: bash -c 'isort "$@" && git add -u' --
        language: python
        args: ["--filter-files"]
        files: \.py$
      - id: black
        name: Black Python code formatting
        entry: bash -c 'black "$@"; git add -u' --
        language: python
        types: [python]
        args: ["--line-length=120"]
      - id: pytest-unit
        files: terra/
        name: Run pytest tests
        stages: [commit]
        types: [python]
        entry: bash -c 'cd terra && pytest -x -m unit' --
        language: system
        pass_filenames: false
        always_run: true
      - id: pytest-integration
        files: terra/
        name: Run pytest tests
        stages: [push]
        types: [python]
        entry: bash -c 'cd terra && pytest -x -m "not unit"' --
        language: system
        pass_filenames: false
        always_run: true
      - id: django-check
        files: terra/
        name: Run django check
        stages: [commit]
        types: [python]
        entry: bash -c 'cd terra && python manage.py check' --
        language: system
        pass_filenames: false
        always_run: true