version: "3.6"

x-terra-opts: &terra-opts
  build: terra/
  image: "dymaxionlabs/platform:latest"
  volumes:
    - ./terra/:/app
  depends_on:
    - db
    - redis
  environment:
    - PIPENV_DONT_LOAD_ENV=1
    - DB_HOST=db
    - DB_NAME=terra
    - DB_USER=postgres
    - RQ_REDIS_URL=redis://redis:6379/0
    - SECRET_KEY=foobar
    - WEBCLIENT_URL=http://localhost:3000
    - SENTRY_DNS=

services:
  db:
    image: mdillon/postgis
    ports:
      - "5433:5432"

  redis:
    image: redis
    ports:
      - "6380:6379"

  terra:
    <<: *terra-opts
    command: [
      "wait-for-postgres.sh", "db",
      "pipenv", "run", "./manage.py", "runserver", "0.0.0.0:8000"
    ]
    ports:
      - "8000:8000"

  terra-worker:
    <<: *terra-opts
    command: [
      "wait-for-postgres.sh", "db",
      "pipenv", "run", "./manage.py", "rqworker"
    ]
