version: "3.3"

services:
  db:
    image: "postgis/postgis:latest"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    labels:
      kompose.volume.size: 1Gi
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  terra:
    build: terra/
    image: dymaxionlabs/terra:latest
    stdin_open: true
    tty: true
    # entrypoint: /bin/bash
    volumes:
      - ./terra/:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis

  aqua:
    build: aqua/
    image: dymaxionlabs/aqua:latest
    stdin_open: true
    tty: true
    volumes:
      - ./aqua/:/app
    ports:
      - "3000:3000"

volumes:
  postgres_data:
