version: "3.3"

services:
  db:
    image: "postgis/postgis:latest"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    labels:
      kompose.volume.size: 1Gi
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"

  terra:
    build: terra/
    image: dymaxionlabs/terra:latest
    stdin_open: true
    tty: true
    env_file: .env.docker
    user: ${UID}:${GID}
    volumes:
      - ./terra/:/app
    ports:
      - "8001:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=terra
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - RQ_REDIS_URL=redis://redis:6379/0
      - WEBCLIENT_URL=http://aqua:3000
    depends_on:
      - db
      - redis

  aqua:
    build: aqua/
    image: dymaxionlabs/aqua:latest
    stdin_open: true
    tty: true
    env_file: .env.docker
    user: ${UID}:${GID}
    volumes:
      - ./aqua/:/app
    ports:
      - "3000:3000"

volumes:
  postgres_data:
