# Generated by Django 2.1.7 on 2019-03-28 17:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotations', '0004_auto_20190221_1147'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quotation',
            new_name='Request',
        ),
        migrations.RenameModel(
            old_name='QuotationArea',
            new_name='RequestArea',
        ),
        migrations.RenameField(
            model_name='requestarea',
            old_name='quotation',
            new_name='request',
        ),
    ]
