# Generated by Django 2.1.7 on 2019-03-28 17:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_rename_requests_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestStateUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PENDING', 'pending'), ('EVALUATING', 'evaluating'), ('AWAITING_PAYMENT', 'awaiting payment'), ('PROCESSING', 'processing'), ('FINISHED', 'finished'), ('CANCELED', 'canceled')], default='PENDING', max_length=24)),
                ('description', models.TextField(blank=True, null=True)),
                ('extra_fields', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_updates', to='quotations.Request')),
            ],
        ),
    ]
