# Generated by Django 3.0.5 on 2020-07-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquota',
            name='max_file_size',
            field=models.BigIntegerField(default=10737418240),
        ),
        migrations.AlterField(
            model_name='userquota',
            name='total_space_per_project',
            field=models.BigIntegerField(default=26843545600),
        ),
    ]
