# Generated by Django 3.0.5 on 2020-07-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotas', '0002_auto_20200724_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquota',
            old_name='total_space_per_project',
            new_name='total_space_per_user',
        ),
        migrations.AlterField(
            model_name='userquota',
            name='max_projects_per_user',
            field=models.IntegerField(default=100),
        ),
    ]
