# Generated by Django 3.0.5 on 2020-07-24 14:16

from django.conf import settings
from django.db import migrations

def quota_initialization(apps, schema_editor):
    MyModel = apps.get_model('quotas', 'UserQuota')
    UserModel = apps.get_model('auth', 'User')
    for user in UserModel.objects.all():
        MyModel.objects.get_or_create(user=user)


def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotas', '0003_auto_20200727_1505'),
    ]

    operations = [
        migrations.RunPython(quota_initialization, reverse_func),
    ]
