# Generated by Django 3.0.5 on 2022-07-29 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotas', '0004_quota_initialization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userquota',
            options={'ordering': ('-created_at',)},
        ),
    ]
