# Generated by Django 2.1.7 on 2019-02-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20190222_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='name',
            field=models.CharField(default='---', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='layer',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
