# Generated by Django 2.1.7 on 2019-02-22 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20190222_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maplayer',
            options={'ordering': ('order',)},
        ),
        migrations.RemoveField(
            model_name='map',
            name='layers',
        ),
        migrations.AddField(
            model_name='maplayer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='layer',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.Layer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='map',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.Map'),
            preserve_default=False,
        ),
    ]
