# Generated by Django 2.1.7 on 2019-02-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20190224_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
