# Generated by Django 2.1.7 on 2019-03-13 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInvitationToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('email', models.CharField(max_length=75, verbose_name='Email')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Confirmed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project invitation token',
                'verbose_name_plural': 'Project invitation tokens',
            },
        ),
        migrations.AlterUniqueTogether(
            name='projectinvitationtoken',
            unique_together={('project', 'email')},
        ),
    ]
