# Generated by Django 3.0.5 on 2020-07-24 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def set_owner(apps, schema_editor):
    MyModel = apps.get_model('projects', 'Project')
    for row in MyModel.objects.all():
        row.owner = row.collaborators.first()
        row.save(update_fields=['owner'])

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0044_auto_20200724_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(set_owner),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
