# Generated by Django 3.0.5 on 2020-07-25 23:27

from django.db import migrations


def rename_projects_with_duplicated_names(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    for project in Project.objects.all():
        count = Project.objects.filter(name=project.name).count()
        if count > 1:
            project.name = f'{project.name} ({count})'
            project.save(update_fields=['name'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_project_owner'),
    ]

    operations = [
        migrations.RunPython(rename_projects_with_duplicated_names, migrations.RunPython.noop),
    ]
