# Generated by Django 3.0.5 on 2020-07-25 23:27

from django.db import migrations
from django.conf import settings


def rename_projects_with_duplicated_names(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    Project = apps.get_model('projects', 'Project')

    for user in User.objects.all():
        user_projects = Project.objects.filter(owner=user)
        for project in user_projects:
            count = user_projects.filter(name=project.name).count()
            if count > 1:
                project.name = f'{project.name} ({count})'
                project.save(update_fields=['name'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_project_owner'),
    ]

    operations = [
        migrations.RunPython(rename_projects_with_duplicated_names, migrations.RunPython.noop),
    ]
