# Generated by Django 3.0.5 on 2020-08-17 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_add_unique_name_in_projects_20200725_2334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
