# Generated by Django 3.0.5 on 2021-02-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_delete_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimators_module',
            field=models.BooleanField(default=True, verbose_name='Enable Estimators module'),
        ),
    ]
