# Generated by Django 3.0.5 on 2021-02-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_project_estimators_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='redash_dashboard_url',
            field=models.URLField(blank=True, verbose_name='Redash Dashboard URL'),
        ),
    ]
