# Generated by Django 3.0.5 on 2021-03-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0051_layer_use_cog_tiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='use_cog_tiles',
            field=models.BooleanField(default=True),
        ),
    ]
