# Generated by Django 3.0.5 on 2021-03-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0053_dashboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="dashboards_module",
            field=models.BooleanField(
                default=False, verbose_name="Enable Dashboards module"
            ),
        ),
    ]
