# Generated by Django 3.0.5 on 2021-03-29 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0055_add_dashboard_from_redash_dashboard_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="redash_dashboard_url",
        ),
    ]
