# Generated by Django 3.0.5 on 2021-04-15 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0056_remove_project_redash_dashboard_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maplayer",
            name="layer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maps",
                to="projects.Layer",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="maplayer",
            unique_together={("map", "layer", "order")},
        ),
    ]
