# Generated by Django 3.0.5 on 2022-08-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0060_auto_20220729_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='estimators_module',
        ),
    ]
