# Generated by Django 3.0.5 on 2023-03-04 21:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0061_remove_project_estimators_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='area_geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
