# Generated by Django 2.1.7 on 2019-03-26 16:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0029_projects_no_images_verbose'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True, verbose_name='task id')),
                ('task_name', models.CharField(max_length=255, null=True, verbose_name='task name')),
                ('task_args', models.TextField(null=True, verbose_name='task arguments')),
                ('task_kwargs', models.TextField(null=True, verbose_name='task kwargs')),
                ('status', models.CharField(choices=[('FAILURE', 'FAILURE'), ('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('RETRY', 'RETRY'), ('REVOKED', 'REVOKED'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS')], default='PENDING', max_length=50, verbose_name='state')),
                ('content_type', models.CharField(max_length=128, verbose_name='content type')),
                ('content_encoding', models.CharField(max_length=64, verbose_name='content encoding')),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(default=None, editable=False, null=True)),
                ('date_done', models.DateTimeField(auto_now=True, verbose_name='done at')),
                ('traceback', models.TextField(blank=True, null=True, verbose_name='traceback')),
                ('hidden', models.BooleanField(db_index=True, default=False, editable=False)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=None, editable=False, null=True)),
                ('project', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='projects.Project')),
            ],
            options={
                'verbose_name': 'task result',
                'verbose_name_plural': 'task results',
                'ordering': ['-date_done'],
            },
        ),
    ]
