# Generated by Django 3.0.5 on 2020-04-20 00:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_file_path'),
        ('tasks', '0002_update_tasks_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('args', models.TextField(null=True, verbose_name='arguments')),
                ('kwargs', models.TextField(null=True, verbose_name='keyword arguments')),
                ('status', models.CharField(choices=[('FAILED', 'FAILED'), ('FINISHED', 'FINISHED'), ('PENDING', 'PENDING'), ('PROGRESS', 'PROGRESS'), ('STARTED', 'STARTED')], default='PENDING', max_length=50, verbose_name='state')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(null=True, verbose_name='finished at')),
                ('traceback', models.TextField(blank=True, null=True, verbose_name='traceback')),
                ('internal_metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.DeleteModel(
            name='TaskResult',
        ),
    ]
