# Generated by Django 3.0.5 on 2020-04-20 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_new_task_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='state',
        ),
    ]
