# Generated by Django 3.0.5 on 2022-07-29 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20200727_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('-created_at',)},
        ),
    ]
