# Generated by Django 2.2 on 2019-04-22 13:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0030_allow_null_in_projects_groups_and_layers_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estimator_type', models.CharField(choices=[('OD', 'Object detection')], default='OD', max_length=2, verbose_name='estimator type')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='project')),
            ],
            options={
                'unique_together': {('project', 'estimator_type', 'name')},
            },
        ),
    ]
