# Generated by Django 2.2 on 2019-04-23 14:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimator',
            name='classes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=list, size=None),
        ),
    ]
