# Generated by Django 2.2 on 2019-04-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_allow_null_in_projects_groups_and_layers_file'),
        ('estimators', '0005_annotation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagetile',
            old_name='x',
            new_name='col_off',
        ),
        migrations.RenameField(
            model_name='imagetile',
            old_name='y',
            new_name='height',
        ),
        migrations.AddField(
            model_name='imagetile',
            name='row_off',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagetile',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='imagetile',
            unique_together={('file', 'col_off', 'row_off', 'width', 'height')},
        ),
    ]
