# Generated by Django 2.2 on 2019-05-06 15:41

from django.db import migrations, models
import estimators.models


class Migration(migrations.Migration):

    dependencies = [
        ('estimators', '0008_estimators_allow_blank_on_image_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetile',
            name='index',
            field=models.IntegerField(default=estimators.models.get_random_integer_value),
        ),
        migrations.AddIndex(
            model_name='imagetile',
            index=models.Index(fields=['file', 'index'], name='estimators__file_id_24b8e8_idx'),
        ),
    ]
