# Generated by Django 2.2.1 on 2019-06-03 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimators', '0010_trainingjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='image_tile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimators.ImageTile', verbose_name='image tile'),
        ),
        migrations.AlterUniqueTogether(
            name='annotation',
            unique_together={('estimator', 'image_tile')},
        ),
    ]
