# Generated by Django 2.2.5 on 2019-10-01 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimators', '0013_predictionjob_result_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimator',
            name='project',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='estimators',
                to='projects.Project',
                verbose_name='project'),
        ),
    ]
