# Generated by Django 2.2.12 on 2020-04-21 17:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimators', '0014_add_project_fk_to_estimators'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimator',
            name='configuration',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True,
                                                                 null=True),
        ),
    ]
