# Generated by Django 3.0.5 on 2020-05-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimators', '0020_migrate_image_tile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetile',
            name='source_image_file',
            field=models.CharField(max_length=255, verbose_name='source image path'),
        ),
    ]
