# Generated by Django 3.0.5 on 2020-06-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimators', '0024_imagetile_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetile',
            name='source_tile_path',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterUniqueTogether(
            name='imagetile',
            unique_together={('source_tile_path', 'source_image_file',
                              'col_off', 'row_off', 'width', 'height')},
        ),
    ]
