# Generated by Django 3.0.5 on 2020-07-06 14:00

from django.db import migrations, models
import estimators.models


class Migration(migrations.Migration):

    dependencies = [
        ('estimators', '0026_auto_20200612_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetile',
            name='source_image_file',
            field=models.CharField(max_length=512, verbose_name='source image path'),
        ),
        migrations.AlterField(
            model_name='imagetile',
            name='tile_file',
            field=models.FileField(max_length=512, upload_to=estimators.models.tile_images_storage_path, verbose_name='image'),
        ),
    ]
