# Generated by Django 3.0.5 on 2020-09-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimators', '0029_remove_projects_file_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimator',
            name='estimator_type',
            field=models.CharField(choices=[('OD', 'Object detection'), ('SG', 'Segmentation')], default='OD', max_length=2, verbose_name='estimator type'),
        ),
    ]
