PENDING = 'PENDING'
STARTED = 'STARTED'
PROGRESS = 'PROGRESS'
CANCELED = 'CANCELED'
FINISHED = 'FINISHED'
FAILED = 'FAILED'

ALL_STATES = sorted([PENDING, STARTED, PROGRESS, CANCELED, FINISHED, FAILED])
