# Generated by Django 3.0.5 on 2022-07-19 22:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0004_auto_20220719_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None, verbose_name='tags'),
        ),
    ]
