# Generated by Django 3.0.5 on 2022-07-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0005_auto_20220719_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mlmodelversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mlmodelversion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
