# Generated by Django 3.0.5 on 2022-08-24 11:02

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0006_auto_20220729_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='description',
            field=mdeditor.fields.MDTextField(default=''),
            preserve_default=False,
        ),
    ]
