# Generated by Django 3.0.5 on 2022-09-01 17:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0007_auto_20220824_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mlmodel',
            options={'verbose_name': 'Model'},
        ),
        migrations.AddField(
            model_name='mlmodelversion',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='parameters'),
        ),
    ]
