# Generated by Django 2.1.5 on 2019-01-29 21:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_auto_20190120_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='areas_geom',
        ),
        migrations.AddField(
            model_name='quotationarea',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotations.Quotation'),
        ),
    ]
