# Generated by Django 2.2 on 2019-04-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0007_auto_20190403_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
