# Generated by Django 2.2.12 on 2020-04-24 19:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('FAILED', 'FAILED'),
                                            ('FINISHED', 'FINISHED'),
                                            ('PENDING', 'PENDING'),
                                            ('STARTED', 'STARTED')],
                                   default='PENDING',
                                   max_length=50,
                                   verbose_name='state'),
        ),
        migrations.CreateModel(
            name='TaskLogEntry',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('logged_at', models.DateTimeField()),
                ('log', django.contrib.postgres.fields.jsonb.JSONField()),
                ('task',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='tasks.Task')),
            ],
        ),
    ]
