# Generated by Django 3.0.5 on 2020-07-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20200724_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='estimated duration'),
        ),
    ]
