# Generated by Django 3.0.5 on 2020-07-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_estimated_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='finished at'),
        ),
    ]
