# Generated by Django 3.0.5 on 2020-07-31 15:59

from django.db import migrations


def add_uses_cloudml_to_tasks_internal_metadata(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    train_predict_tasks = Task.objects.filter(name__in=[
        'estimators.tasks.start_training_job',
        'estimators.tasks.start_prediction_job'
    ])
    for task in train_predict_tasks:
        task.internal_metadata['uses_cloudml'] = True
        task.save(update_fields=['internal_metadata'])


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_set_finished_at_20200726_1509'),
    ]

    operations = [
        migrations.RunPython(add_uses_cloudml_to_tasks_internal_metadata,
                             migrations.RunPython.noop),
    ]
