# Generated by Django 3.0.5 on 2020-08-05 14:25

from django.db import migrations


def empty_args_kwargs(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    for task in Task.objects.all():
        task.args = 'null'
        task.kwargs = 'null'
        task.save(update_fields=['args', 'kwargs'])


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_add_uses_cloudml_to_tasks_internal_metadata'),
    ]

    operations = [
        migrations.RunPython(empty_args_kwargs, migrations.RunPython.noop),
    ]
