# Generated by Django 3.0.5 on 2020-08-05 14:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_empty_args_kwargs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='args',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=list, verbose_name='arguments'),
        ),
        migrations.AlterField(
            model_name='task',
            name='kwargs',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, verbose_name='keyword arguments'),
        ),
    ]
