# Generated by Django 3.0.5 on 2020-08-05 14:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_fix_args_kwargs_internal_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='internal_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='internal metadata'),
        ),
        migrations.AlterField(
            model_name='task',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='metadata'),
        ),
    ]
