# Generated by Django 3.0.5 on 2020-08-05 14:43

from django.db import migrations


def delete_tasks_with_no_name(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    for task in Task.objects.filter(name=None):
        task.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_add_defaults_to_metadata_internal_metadata'),
    ]

    operations = [
        migrations.RunPython(delete_tasks_with_no_name,
                             migrations.RunPython.noop),
    ]
