# Generated by Django 3.0.5 on 2020-08-05 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_disallow_null_on_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklogentry',
            options={'verbose_name': 'task log entry', 'verbose_name_plural': 'task log entries'},
        ),
    ]
